sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install lib32z1 lib32ncurses5
  
language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email: false

script:
  - "./gradlew clean clearJarCopy build createExe copyJars"

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gclapY/XkzD7WS6lwDzCuMfrBeOpuSU2GspKegWOR2aJc0QZeu6vfJh3ioPJ4ids2ySTiNk1ts7Q34oN5OvHtww4lc5inmg0EThz0/NU+/fgxmDU2j99KMCeqlxPkFnCosjCcmk/s+ry4VUJFaOgT30yY6iA2JAxcSCEuIS1ExDIbErmMTdnwJ9kTS+nHNcG9Ny/qpBZhwhsxBbXI78bdN2lQc+etzewYQ9AeQVGUd9v1trGYkq01ePi4JJO5qDPk7indrOl9sLZWlYgO1XCSgqUULOhtgnXwu9DBb/MCUrSgugQL5f4J/HOvAqYYisp9jPGtHxFWtKhWJdbnoWcZziU6XAK2oMH4I1tdr5q5gc/t0Scsr5i91XHuU+wjKU9thhihLnV/ANbwH+RepOsk4Q9d14W8wAKr3JQZCZqyyeJUtHodiDvHhO6bPiMloIuFtmyCQc62KutBkNYOtMQ9KviZnt2Q6UUisKAC/NXJsVbwAmJbgzdqZuGU7c2hVxRHruIsKvpaBYju0rZy1c796VlEESIAy8mdGPiqt/Opsc4JGVoaDoed5sBOZH+WQNLFStFDgYDzR7FotbJmFQ1uLe9xOtbOqh2QkTP8NISii7PSEMbBivS3sZJHNB06QBFr80nfsPJdJRDDj+R2fpQj0wA0iYnJ+8QJH6+vOowRoI=
  file_glob: true
  file: 
    - "jarCopys/*"
    - "servercontroller-core/build/launch4j/*.exe"
  name: "${TRAVIS_BUILD_NUMBER}-${TRAVIS_BRANCH}-${TRAVIS_BUILD_ID}"
  on:
    branch: master
    repo: SE7-KN8/ServerController
    tags: true
after_deploy:
  - "./gradlew clearJarCopy"
